[tool.poetry]
name = "django"
version = "0.1.0"
description = ""
authors = ["worldunion <huangwein@worldunion.com.cn>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
